logo: Home # add logo name
title: Steven Schepanski - Portfolio
description: > # this means to ignore newlines until "baseurl:"
   Write an awesome description for your new site here. You can edit this
   line in _config.yml. It will appear in your document head meta (for
   Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/test" # the subpath of your site, e.g. /blog
url: "stevenschepanski.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Steven Schepanski # banner title
banner-desc: Engineering Project Portfolio # banner description

# Author settings
author-pic: headshot.jpg # your photo
author-name: Steven Schepanski # your name
about-author: Testing the Author Bio 
              More about the author? # about author
email: sschepanski@gmail.com # your email
phone: (561)-926-1227 # your pnone number
# website:  # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
linkedin_url:  # dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier: mr-brown # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
